# 使用するライブラリの読み込み

In [8]:
import pandas as pd
import re
import datetime
from datetime import timedelta
import time
import glob

# 各種テーブルの読み込み

In [9]:
start = 2018
end = 2024

## レース結果の読み込み

In [10]:
def makedataRaceResults(dataUpdate=False):
    """
    レース結果のデータを作成する関数  
    rowdataに更新があった場合は,`dataUpdate=True`を指定
    """

    raceResults = pd.DataFrame()
    
    if dataUpdate == True:#データに更新があった場合はrowdataを読み込む
        for year in range(start,end + 1):
            files = glob.glob(f"../data/rawData/raceResults/{year}*")
            files.sort()

            cnt = 1
            for file in files:
                print("\r" + "(" + str(cnt) + "/" + str(len(files)) + ")",end="")

                dftmp = pd.read_pickle(file)
                raceResults = pd.concat([raceResults,dftmp])

                cnt += 1
            
            print("\r" + f"{year}年の{cnt}レースの結果を読み込みました")

        raceResults.to_pickle("../data/tmpData/raceResults.pickle")
    else:
        raceResults = pd.read_pickle("../data/tmpData/raceResults.pickle")

    return raceResults

In [11]:
raceResults = makedataRaceResults(dataUpdate=False)

In [12]:
raceResults.head(5)

,着 順,枠 番,馬 番,馬名,性齢,斤量,騎手,タイム,着差,単勝,人 気,馬体重,調教師,raceID,horseID,jockeyID
0,1,1,1,コントラチェック,牝2,54.0,ルメール,1:50.1,NaN,1.1,1.0,458(+4),[東] 藤沢和雄,201801010101,2016104880,05339
1,2,6,6,ブラックウォーリア,牡2,54.0,岩田康誠,1:51.3,7,7.6,2.0,488(+6),[西] 西村真幸,201801010101,2016101840,05203
2,3,3,3,テングレート,牡2,54.0,丸山元気,1:51.4,1/2,8.3,3.0,480(-6),[東] 金成貴史,201801010101,2016105057,01127
3,4,4,4,イチザテイオー,牡2,54.0,松岡正海,1:52.3,5,46.7,5.0,460(-8),[西] 西橋豊治,201801010101,2016103985,01085
4,5,5,5,トーセンイマジン,牡2,52.0,横山武史,1:53.5,7,39.8,4.0,470(-8),[東] 土田稔,201801010101,2016103821,01170

## レース情報の読み込み

In [13]:
def makedataRaceInfos(dataUpdate=False):
    """
    レース情報のデータを作成する関数  
    rowdataに更新があった場合は,`dataUpdate=True`を指定
    """
    
    raceInfos = pd.DataFrame()

    if dataUpdate == True:#データの更新があった場合はrawdataを読み込む
        for year in range(start,end + 1):
            #読み込み対象ファイルリストの作成
            files = glob.glob(f"../data/rawData/raceInfos/{year}*")
            files.sort()

            #データの読み込み
            cnt = 1
            for file in files:
                print("\r" + "(" + str(cnt) + "/" + str(len(files)) + ")",end="")

                dftmp = pd.read_pickle(file)
                raceInfos = pd.concat([raceInfos,dftmp])

                cnt += 1
            
            print("\r" + f"{year}年の{cnt}レースの結果を読み込みました")

        raceInfos.to_pickle("../data/tmpData/raceInfos.pickle")
    else:
        raceInfos = pd.read_pickle("../data/tmpData/raceInfos.pickle")

    return raceInfos

In [14]:
raceInfos = makedataRaceInfos(dataUpdate=False)

In [15]:
raceInfos.head(5)

         raceID raceName course_len weather raceType groundState        date
0  201801010101    2歳未勝利       1800       晴        芝           良  2018年7月28日
0  201801010102    3歳未勝利       1000       晴      ダート           良  2018年7月28日
0  201801010103    3歳未勝利       2400       晴      ダート           良  2018年7月28日
0  201801010104    3歳未勝利       1700       晴      ダート           良  2018年7月28日
0  201801010105     2歳新馬       1500       晴        芝           良  2018年7月28日

## 馬の過去成績の読み込み

In [16]:
def makedataHorseResults(dataUpdate=False):
    """
    馬の過去成績のデータを作成する関数  
    rowdataに更新があった場合は,`dataUpdate=True`を指定  
    `horseIDList`の作成に`raceResults`を使用するため、事前に作成の必要あり
    """

    horseResults = pd.DataFrame()

    if dataUpdate == True:
        #horseIDListの作成
        horseIDList = raceResults["horseID"].unique()
        horseIDList.sort()

        cnt = 1
        for horseID in horseIDList:
            print("\r" + "(" + str(cnt) + "/" + str(len(horseIDList)) + ")",end="")

            dftmp = pd.read_pickle(f"../data/rawData/horse/{horseID}.pickle")

            indexdf = []
            for i in range(len(dftmp)):
                indexdf.append(horseID)

            dftmp.index = indexdf
            horseResults = pd.concat([horseResults,dftmp])
            cnt += 1
        
        horseResults.to_pickle("../data/tmpData/horseResults.pickle")
        print("\r" + f"horseResultsは{len(horseResults)}レコードです")

    else:
        horseResults = pd.read_pickle("../data/tmpData/horseResults.pickle")

    return horseResults

In [17]:
horseResults = makedataHorseResults(dataUpdate=False)

In [18]:
horseResults.head(5)

,日付,開催,天 気,R,レース名,映 像,頭 数,枠 番,馬 番,オ ッ ズ,...,着差,ﾀｲﾑ 指数,通過,ペース,上り,馬体重,厩舎 ｺﾒﾝﾄ,備考,勝ち馬 (2着馬),賞金
2006106754,2018/03/24,3中山1,晴,11.0,日経賞(GII),NaN,15.0,5.0,8,625.9,...,5.5,**,14-14-14-15,31.0-36.0,38.0,452(-6),NaN,NaN,ガンコ,NaN
2006106754,2018/02/17,1東京7,晴,11.0,ダイヤモンドS(GIII),NaN,14.0,7.0,11,403.8,...,6.8,**,14-14-14-14,36.9-35.8,40.0,458(+6),NaN,NaN,フェイムゲーム,NaN
2006106754,2018/01/07,1京都2,晴,11.0,万葉S(OP),NaN,9.0,3.0,3,115.1,...,2.8,**,9-9-9-9,36.7-35.8,37.1,452(-2),NaN,NaN,トミケンスラーヴァ,NaN
2006106754,2017/12/02,5中山1,晴,11.0,ステイヤーズS(GII),NaN,10.0,7.0,8,133.0,...,11.1,**,10-10-10-10,37.6-35.5,43.0,454(-10),NaN,NaN,アルバート,NaN
2006106754,2017/02/18,1東京7,曇,11.0,ダイヤモンドS(GIII),NaN,15.0,7.0,13,154.8,...,2.8,**,15-15-14-14,38.3-34.4,35.7,464(0),NaN,NaN,アルバート,NaN

## 馬の血統情報の読み込み

In [19]:
def makedataHorsePED(dataUpdate=False):
    """
    馬の血統情報のデータを作成する関数  
    rowdataに更新があった場合は,`dataUpdate=True`を指定  
    `horseIDList`の作成に`raceResults`を使用するため、事前に作成の必要あり
    """
    horsePED = pd.DataFrame()

    if dataUpdate == True:
        #horseIDListの作成
        horseIDList = raceResults["horseID"].unique()
        horseIDList.sort()

        cnt = 1
        for horseID in horseIDList:
            print("\r" + "(" + str(cnt) + "/" + str(len(horseIDList)) + ")",end="")

            dftmp = pd.read_pickle(f"../data/rawData/ped/{horseID}.pickle")
            horsePED =  pd.concat([horsePED,dftmp])
            cnt += 1

        horsePED.to_pickle("../data/tmpData/horsePED.pickle")
        print("\n" + f"horsePEDは{len(horsePED)}レコードです")
    else:
        horsePED = pd.read_pickle("../data/tmpData/horsePED.pickle")

    return horsePED

In [20]:
horsePED = makedataHorsePED(dataUpdate=False)

In [21]:
horsePED.head(5)

,F,FF,FFF,FFFF,FFFFF,FFFFM,FFFM,FFFMF,FFFMM,FFM,...,MMFM,MMFMF,MMFMM,MMM,MMMF,MMMFF,MMMFM,MMMM,MMMMF,MMMMM
2006106754,ゴールドアリュール,サンデーサイレンス,Halo,Hail to Reason,Turn-to,Nothirdchance,Cosmah,Cosmic Bomb,Almahmoud,Wishing Well,...,Sweet Tooth,On-And-On,Plum Cake,Fleet Victress,King of the Tudors,Tudor Minstrel,Glen Line,Countess Fleet,Count Fleet,Honor Bound
2007100107,アドマイヤマックス,サンデーサイレンス,Halo,Hail to Reason,Turn-to,Nothirdchance,Cosmah,Cosmic Bomb,Almahmoud,Wishing Well,...,Alluvial,Buckpasser,Bayou,エイプリルソネット,Dike,Herbager,Delta,Pass Me,Pass,Schooner
2007100828,スウェプトオーヴァーボード,エンドスウィープ,フォーティナイナー,Mr. Prospector,Raise a Native,Gold Digger,File,Tom Rolfe,Continue,Broom Dance,...,Anguar,Verso,La Rochelle,Marston's Mill,In Reality,Intentionally,My Dear Girl,Millicent,Cornish Prince,Milan Mill
2007106312,ホワイトマズル,ダンシングブレーヴ,Lyphard,Northern Dancer,Nearctic,Natalma,Goofed,Court Martial,Barra,Navajo Princess,...,Lady Victoria,Victoria Park,Lady Angela,サンドラターフ,ヒッティングアウェー,Ambiorix,Striking,ロイヤルレジナ,Fleet Nasrullah,Fine Catch
2008100175,デュランダル,サンデーサイレンス,Halo,Hail to Reason,Turn-to,Nothirdchance,Cosmah,Cosmic Bomb,Almahmoud,Wishing Well,...,Quick Cure,Dr. Fager,Speedwell,Lake Champlain,Kings Lake,Nijinsky,Fish - Bar,Sensibility,Hail to Reason,Pange

# 前処理

## カラム名称の変更  
レース結果/馬過去成績テーブルに半角スペースを含むカラム名があるので、半角スペースを削除

In [22]:
raceResults = raceResults.rename(columns={
    "着 順":"着順",
    "枠 番":"枠番",
    "馬 番":"馬番",
    "人 気":"人気"})

In [23]:
horseResults = horseResults.rename(columns={
    "天 気":"天気",
    "映 像":"映像",
    "頭 数":"頭数",
    "枠 番":"枠番",
    "馬 番":"馬番",
    "オ ッ ズ":"オッズ",
    "人 気":"人気",
    "着 順":"着順",
    "斤 量":"斤量",
    "馬場":"馬場",
    "馬場 指数":"馬場指数",
    "ﾀｲﾑ 指数":"タイム指数",
    "厩舎 ｺﾒﾝﾄ":"厩舎コメント",
    "勝ち馬 (2着馬)":"勝ち馬(2着馬)"})

## テーブルの結合
レース結果テーブルとレース情報テーブルを内部結合

In [24]:
raceResultsAdd = raceResults.merge(raceInfos, left_on = "raceID", right_on = "raceID", how = "inner")

In [25]:
pd.set_option('display.max_columns', raceResultsAdd.shape[1])
raceResultsAdd.head()

,着順,枠番,馬番,馬名,性齢,斤量,騎手,タイム,着差,単勝,人気,馬体重,調教師,raceID,horseID,jockeyID,raceName,course_len,weather,raceType,groundState,date
0,1,1,1,コントラチェック,牝2,54.0,ルメール,1:50.1,NaN,1.1,1.0,458(+4),[東] 藤沢和雄,201801010101,2016104880,05339,2歳未勝利,1800,晴,芝,良,2018年7月28日
1,2,6,6,ブラックウォーリア,牡2,54.0,岩田康誠,1:51.3,7,7.6,2.0,488(+6),[西] 西村真幸,201801010101,2016101840,05203,2歳未勝利,1800,晴,芝,良,2018年7月28日
2,3,3,3,テングレート,牡2,54.0,丸山元気,1:51.4,1/2,8.3,3.0,480(-6),[東] 金成貴史,201801010101,2016105057,01127,2歳未勝利,1800,晴,芝,良,2018年7月28日
3,4,4,4,イチザテイオー,牡2,54.0,松岡正海,1:52.3,5,46.7,5.0,460(-8),[西] 西橋豊治,201801010101,2016103985,01085,2歳未勝利,1800,晴,芝,良,2018年7月28日
4,5,5,5,トーセンイマジン,牡2,52.0,横山武史,1:53.5,7,39.8,4.0,470(-8),[東] 土田稔,201801010101,2016103821,01170,2歳未勝利,1800,晴,芝,良,2018年7月28日

## データ型の変更と内容の修正

### レース結果テーブル

In [26]:
def raceResultsPreProcessing(results):
    df = results.copy()
    
    #着順 → Rank
    df["Rank"] = df["着順"].astype(str).str.strip("()降再")
    df = df[df["Rank"].astype(str).str.contains("\d")]
    df["Rank"] = df["Rank"].astype(int)
    
    #性齢 → Sex/Age
    df["Sex"] = df["性齢"].astype(str).str[:1]
    df["Age"] = df["性齢"].str.extract(r'(\d+)').astype(int)
    
    #馬体重 →Weight/WeightVariation
    df = df[df["馬体重"].astype(str).str.contains("\d")]
    df["Weight"] = df["馬体重"].str.split("(",expand=True)[0].astype(int)
    df["WeightVariation"] = df["馬体重"].str.split("(",expand=True)[1].str[:-1].astype(int)
    
    #変数の型を修正
    df["単勝"] = df["単勝"].astype(float)
    df["斤量"] = df["斤量"].astype(int)
    df["人気"] = df["人気"].astype(int)
    df["枠番"] = df["枠番"].astype(int)
    df["馬番"] = df["馬番"].astype(int)
    df["course_len"] = df["course_len"].astype(int)
    df["date"] = pd.to_datetime(df["date"],format="%Y年%m月%d日")
    #不要変数の削除
    df.drop(columns=["タイム","着差","調教師","騎手","馬名","着順","性齢","馬体重"], inplace=True)
    
    return df

In [27]:
raceResultsFin = raceResultsPreProcessing(raceResultsAdd)

In [29]:
raceResultsFin["date"]

0        2018-07-28
1        2018-07-28
2        2018-07-28
3        2018-07-28
4        2018-07-28
            ...
311121   2024-07-21
311122   2024-07-21
311123   2024-07-21
311124   2024-07-21
311125   2024-07-21
Name: date, Length: 308474, dtype: datetime64[ns]

### 馬過去成績テーブル

In [22]:
def horseResultsPreProcessing(horseResults):
    df = horseResults.copy()

    #着順 → Rank
    df["Rank"] = df["着順"].astype(str).str.strip("()降再")
    df = df[df["Rank"].astype(str).str.contains("\d")]
    df["Rank"] = df["Rank"].astype(float)
    df["Rank"] = df["Rank"].astype(int)

    #変数の型を修正
    df["date"] = pd.to_datetime(df["日付"])

    #不要変数の削除
    df.drop(columns=["着順","日付"], inplace=True)

    return df

In [23]:
horseResultsFin = horseResultsPreProcessing(horseResults)

# 変数作成

## 馬の過去成績に関する変数

In [ ]:
def makeVarFromHorseResults(dftmp):
    """
    馬の過去成績から変数を作成し、dftmpに指定したテーブルに追加する関数  
    作成変数===================  
    pre1Rank  :前1走の順位  
    pre2Rank  :前2走の順位  
    pre3Rank  :前3走の順位  
    pre4Rank  :前4走の順位  
    pre5Rank  :前5走の順位  
    preAllRank:過去すべての順位の平均  
    pre1Term  :前1走から今回までの期間(日)  
    pre2Term  :前2走から前1走までの期間(日)  
    pre3Term  :前3走から前2走までの期間(日)  
    pre4Term  :前4走から前3走までの期間(日)  
    pre5Term  :前5走から前4走までの期間(日)
    """
    dftgt = dftmp.copy()
    #レース結果テーブルからのindexをカラムhorseIDとして取得
    #dftgt.reset_index(inplace= True)
    #dftgt = dftgt.rename(columns={'index': 'raceID'})

    dftmpFin = dftgt.copy()

    #過去の順位系の変数作成===================================================================================================
    #pre1Rank,pre2Rank,pre3Rank,preAllRankMean

    #馬結果テーブルを中央の結果のみにする
    forPreRank = horseResultsFin[horseResultsFin['開催'].str.contains("札幌|函館|福島|新潟|東京|中山|中京|京都|阪神|小倉")]
    #レース結果テーブルと馬結果テーブルを結合(Rank,date,)
    forPreRank2 = dftgt.merge(forPreRank[["Rank","date"]], left_on = "horseID", right_index = True, how = "left")
    #対象レースより過去の日付の結果のみに絞る
    forPreRank2 = forPreRank2[forPreRank2["date_x"] > forPreRank2["date_y"]]
    #レースID,horseIDをキーに連番をふる(何個前のレースかの番号)
    forPreRank2["no"] = forPreRank2.groupby(["raceID","horseID"]).cumcount()

    #過去レースの順位テーブルを作成
    for i in range(5):
        preRankTmp = pd.DataFrame()
        preRankTmp = forPreRank2[forPreRank2["no"] == i][["raceID","horseID","Rank_y"]]
        preRankTmp.rename(columns={'Rank_y': f'pre{str(i + 1)}Rank'},inplace=True)
        dftmpFin = dftmpFin.merge(preRankTmp, left_on=["raceID","horseID"],right_on=["raceID","horseID"],how="left")

    preAllRankMean = forPreRank2.groupby(["raceID","horseID"]).mean("Rank_y")
    preAllRankMean.rename(columns={"Rank_y":"preAllRankMean"},inplace=True)
    dftmpFin = dftmpFin.merge(preAllRankMean["preAllRankMean"],left_on=["raceID","horseID"],right_index=True,how="left")
    #過去実績のない馬に対する処理を追加する必要あり

    #過去のレース間日数系の変数作成============================================================================================
    #pre1Term,pre2Term,pre3Term
    #レース結果テーブルと馬結果テーブルを結合(Rank,date,)
    forPreTerm = dftgt.merge(horseResultsFin[["Rank","date"]], left_on = "horseID", right_index = True, how = "left")
    #対象レースより過去の日付の結果のみに絞る
    forPreTerm = forPreTerm[forPreTerm["date_x"] > forPreTerm["date_y"]]
    #レースID,horseIDをキーに連番をふる(何個前のレースかの番号)
    forPreTerm["no"] = forPreTerm.groupby(["raceID","horseID"]).cumcount()

    #過去のレース間の日数を算出
    preTermFin = pd.DataFrame()
    termColumnsList = ["raceID","horseID"]
    for i in range(5):
        preTermTmp = forPreTerm[forPreTerm["no"] == i][["raceID","horseID","date_x","date_y"]]
        preTermTmp.rename(columns={"date_y":f"pre{str(i + 1)}date"},inplace=True)

        if i == 0 :
            preTermFin = preTermTmp
            preTermFin.rename(columns={"date_x":"pre0date"},inplace=True)
        else:
            preTermFin = preTermFin.merge(preTermTmp[["raceID","horseID",f"pre{str(i + 1)}date"]],left_on=["raceID","horseID"],right_on=["raceID","horseID"],how="left")

        preTermFin[f"pre{str(i + 1)}Term"] = preTermFin[f"pre{str(i)}date"] - preTermFin[f"pre{str(i + 1)}date"]
        preTermFin[f"pre{str(i + 1)}Term"] = preTermFin[f"pre{str(i + 1)}Term"] / timedelta(days=1)
        termColumnsList.append(f"pre{str(i + 1)}Term")

    #dftmpにレース間日数情報を結合
    dftmpFin = dftmpFin.merge(preTermFin[termColumnsList],left_on=["raceID","horseID"],right_on=["raceID","horseID"],how="left")

    return dftmpFin

In [25]:
forModelingDFtmp1 = makeVarFromHorseResults(raceResultsFin)

In [26]:
pd.set_option('display.max_columns', forModelingDFtmp1.shape[1])
forModelingDFtmp1.head()

,枠番,馬番,斤量,単勝,人気,raceID,horseID,jockeyID,raceName,course_len,weather,raceType,groundState,date,Rank,Sex,Age,Weight,WeightVariation,pre1Rank,pre2Rank,pre3Rank,pre4Rank,pre5Rank,preAllRankMean,pre1Term,pre2Term,pre3Term,pre4Term,pre5Term
0,1,1,54,1.1,1,201801010101,2016104880,05339,2歳未勝利,1800,晴,芝,良,2018-07-28,1,牝,2,458,4,3.0,NaN,NaN,NaN,NaN,3.0,20.0,NaN,NaN,NaN,NaN
1,6,6,54,7.6,2,201801010101,2016101840,05203,2歳未勝利,1800,晴,芝,良,2018-07-28,2,牡,2,488,6,4.0,5.0,NaN,NaN,NaN,4.5,7.0,13.0,NaN,NaN,NaN
2,3,3,54,8.3,3,201801010101,2016105057,01127,2歳未勝利,1800,晴,芝,良,2018-07-28,3,牡,2,480,-6,5.0,NaN,NaN,NaN,NaN,5.0,13.0,NaN,NaN,NaN,NaN
3,4,4,54,46.7,5,201801010101,2016103985,01085,2歳未勝利,1800,晴,芝,良,2018-07-28,4,牡,2,460,-8,11.0,NaN,NaN,NaN,NaN,11.0,6.0,NaN,NaN,NaN,NaN
4,5,5,52,39.8,4,201801010101,2016103821,01170,2歳未勝利,1800,晴,芝,良,2018-07-28,5,牡,2,470,-8,7.0,NaN,NaN,NaN,NaN,7.0,13.0,NaN,NaN,NaN,NaN

In [27]:
#一旦保存
forModelingDFFin = forModelingDFtmp1
forModelingDFFin.to_pickle("../data/forModeling/forModelingDF.pickle")

## 血統に関する変数

In [60]:
pedInfotmp = pd.DataFrame()
pedInfotmp[["開催","賞金","Rank","date"]] = horseResultsFin[["開催","賞金","Rank","date"]]
pedInfotmp.reset_index(inplace=True)
pedInfotmp.rename(columns={"index":"horseID"},inplace=True)
pedInfotmp = pedInfotmp[pedInfotmp['開催'].str.contains("札幌|函館|福島|新潟|東京|中山|中京|京都|阪神|小倉")]
pedInfotmp["year"] = pedInfotmp["date"].dt.year
pedInfotmp = pedInfotmp[(start - 1 <= pedInfotmp["year"]) & (pedInfotmp["year"] <= end - 1)]

In [61]:
#年間勝利数を計算
pedInfotmpWin = pedInfotmp[pedInfotmp["Rank"] == 1]
pedInfotmpWinCnt = pedInfotmpWin[["year","horseID","Rank"]].groupby(["year","horseID"]).count()
pedInfotmpWinCnt.reset_index(inplace=True)
pedInfotmpWinCnt.rename(columns={"Rank":"WinCnt"},inplace=True)
pedInfotmpWinCnt = pedInfotmpWinCnt.merge(horsePED[["F","MF"]],left_on="horseID",right_index=True,how="left")
winCntF = pedInfotmpWinCnt.groupby(["year","F"]).sum("WinCnt")
winCntF.reset_index(inplace=True)
winCntMF = pedInfotmpWinCnt.groupby(["year","MF"]).sum("WinCnt")
winCntMF.reset_index(inplace=True)

In [62]:
winCntF

   year          F  WinCnt
0  2018  ディープインパクト       1
1  2018    ブラックタイド       1
2  2018  ヴィクトワールピサ       1

In [63]:
pedInfoRaceAll = pedInfotmp[["year","horseID","date"]].groupby(["year","horseID"]).count()
pedInfoRaceAll.reset_index(inplace=True)
pedInfoRaceAll.rename(columns={"date":"raceCnt"},inplace=True)
pedInfoRaceAll = pedInfoRaceAll.merge(horsePED[["F","MF"]],left_on="horseID",right_index=True,how="left")
RaceAllF = pedInfoRaceAll.groupby(["year","F"]).sum("raceCnt")
RaceAllF.reset_index(inplace=True)
RaceAllMF = pedInfoRaceAll.groupby(["year","MF"]).sum("raceCnt")
RaceAllMF.reset_index(inplace=True)

In [64]:
RaceAllF

   year          F  raceCnt
0  2018  アイルハヴアナザー        5
1  2018  ディープインパクト        3
2  2018  トーセンジョーダン        3
3  2018    ブラックタイド        7
4  2018      ベーカバド        3
5  2018  ヴィクトワールピサ        6

In [65]:
#年間賞金を計算
pedInfotmpPrize = pedInfotmp[["year","horseID","賞金"]].groupby(["year","horseID"]).sum("賞金")
pedInfotmpPrize.reset_index(inplace=True)
pedInfotmpPrize.rename(columns={"賞金":"Prize"},inplace=True)
pedInfotmpPrize = pedInfotmpPrize.merge(horsePED[["F","MF"]],left_on="horseID",right_index=True,how="left")
PrizeF = pedInfotmpPrize.groupby(["year","F"]).sum("Prize")
PrizeF.reset_index(inplace=True)
PrizeMF = pedInfotmpPrize.groupby(["year","MF"]).sum("Prize")
PrizeMF.reset_index(inplace=True)

In [66]:
PrizeF

   year          F   Prize
0  2018  アイルハヴアナザー   125.0
1  2018  ディープインパクト  1086.6
2  2018  トーセンジョーダン     0.0
3  2018    ブラックタイド  1245.0
4  2018      ベーカバド    75.0
5  2018  ヴィクトワールピサ  1035.0