In [3]:
import datetime
from monthdelta import monthmod
from dateutil.relativedelta import relativedelta
import requests
from bs4 import BeautifulSoup
import time
import random
import my_snipets
import pandas as pd
import os
import re
from io import StringIO

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.chrome.options import Options

from tqdm.notebook import tqdm

In [207]:
class makeRaceData:

    def __init__(self, startYM:str, endYM:str):
        self.startYM = startYM
        self.endYM = endYM
        print(f"{self.startYM}～{self.endYM}のレース情報のデータを作成します。")

    def makeYMList(self):
        """
        (year,month)のリストを作成するメソッド
        """
        self.YMList = []

        start = datetime.date(int(self.startYM[0:4]),int(self.startYM[4:]),1)
        end = datetime.date(int(self.endYM[0:4]),int(self.endYM[4:]),1)
        diff = monthmod(start,end)

        for i in tqdm(range(0,diff[0].months + 1),desc="makeYMList"):
            tgt = start + relativedelta(months=i)
            tgtYM = (str(tgt.year),str(tgt.month).zfill(2))
            self.YMList.append(tgtYM)


    def makeRaceDateURLList(self):
        """
        対象日付の開催レース一覧ページのURLを生成する関数
        `date`: 対象の年月日 (datetime.dateオブジェクト)
        """
        self.raceDateURLList = []
        for year , month in tqdm(self.YMList,desc="makeRaceDateURLList"):
            #対象年月の開催カレンダーのURLを生成
            url = f"https://race.netkeiba.com/top/calendar.html?year={year}&month={month}"
            #カレンダーページのHTMLを取得
            headers = {'User-Agent': random.choice(my_snipets.makeUserAgents())}
            html = requests.get(url, headers=headers)
            html.encoding = "EUC-JP"

            #HTMLをsoupオブジェクトに変換
            soup = BeautifulSoup(html.text)

            #開催日の一覧を取得し、開催日ページのURLを取得
            RaceCellBoxAll = soup.find_all("td",attrs={"class":"RaceCellBox"})
            
            for i in range(len(RaceCellBoxAll)):
                if RaceCellBoxAll[i].find("a") is not None:
                    self.raceDateURLList.append(RaceCellBoxAll[i].find("a")["href"].replace("..","https://race.netkeiba.com/"))

            time.sleep(2)

    def makeRaceURLList(self):
        """
        開催日ページのURLから、レースIDのリストを作成する関数
        """

        self.raceIDList = []

        with tqdm(self.raceDateURLList) as urlPbar:
            urlPbar.set_description(desc="makeRaceURLList")
            for tgtURL in urlPbar:
                dateStr = tgtURL.split("=")[1]
                #urlPbar.set_postfix(dateStr)
                # Seleniumを使用してブラウザを起動し、対象URLにアクセス
                option = Options()
                option.add_argument('--headless')
                browser = webdriver.Chrome(options=option)
                browser.get(tgtURL)

                # ブラウザから必要な情報を取得
                RaceListDataItemAll = browser.find_elements(By.CLASS_NAME,"RaceList_DataItem")
                for item in tqdm(RaceListDataItemAll,desc=dateStr, leave=False):
                    raceURL = item.find_element(By.TAG_NAME,"a").get_attribute("href")
                    self.raceIDList.append(re.sub(r"\D+", "", str(raceURL.split("/")[-1:])))

                # ブラウザを閉じる
                browser.quit()

                time.sleep(2)

    def screpingRaceHTML(self,skip:bool=True):
        """
        receIDリストに含まれるレースの結果ページのHTMLをスクレイピングする
        """
        with tqdm(self.raceIDList) as urlPbar:
            urlPbar.set_description("screpingRaceHTML")
            for raceID in urlPbar:
                urlPbar.set_postfix({"raceID":raceID})
                if skip == False or os.path.isfile(f"../data/html/race/{raceID}.txt") == False:
                    url = "https://db.netkeiba.com/race/" + raceID
                    headers = {'User-Agent': random.choice(my_snipets.makeUserAgents())}
                    html = requests.get(url, headers=headers)
                    html.encoding = "EUC-JP"

                    with open(f"../data/html/race/{raceID}.txt","w") as f:
                        f.write(html.text)

                    time.sleep(2)

    def makeRawDataRace(self,skip:bool = True):
        """
        html/raceに格納されているhtmlからレース結果/レース情報/払い戻し情報のrawデータを作成する関数
        """
        with tqdm(self.raceIDList) as urlPbar:
            urlPbar.set_description("makeRawDataRace")               
            for raceID in urlPbar:
                if skip == False or os.path.isfile(f"../data/rawData/raceResults/{raceID}.pickle") == False or os.path.isfile(f"../data/rawData/raceInfos/{raceID}.pickle") == False or os.path.isfile(f"../data/rawData/return/{raceID}.pickle") == False:
                    urlPbar.set_postfix({"raceID":raceID})
                    #共通処理======================================================================================================================
                    with open(f"../data/html/race/{raceID}.txt","r") as f:
                        html = f.read()

                    soup = BeautifulSoup(html) #htmlをsoupオブジェクトへ
                    
                    #receResultsに関する処理=======================================================================================================
                    if skip == False or os.path.isfile(f"../data/rawData/raceResults/{raceID}.pickle") == False:
                        raceResults = pd.DataFrame() #最終出力データセットの定義
                        dfRace = pd.read_html(StringIO(str(soup("table")[0])))[0] #HTMLからレース結果を取得し、DataFrameへ

                        dfRace["raceID"] = raceID

                        horseIDList = []
                        horseAList = soup.find("table",attrs={"summary":"レース結果"}).find_all("a",attrs={"href":re.compile("^/horse")})
                        for a in horseAList:
                            horseID = re.findall("\d+",a["href"])
                            horseIDList.append(horseID[0])
                            
                        dfRace["horseID"] = horseIDList

                        jockeyIDList = []
                        jockeyAList = soup.find("table",attrs={"summary":"レース結果"}).find_all("a",attrs={"href":re.compile("^/jockey")})
                        for a in jockeyAList:
                            jockeyID = re.findall("\d+",a["href"])
                            jockeyIDList.append(jockeyID[0])

                        dfRace["jockeyID"] = jockeyIDList

                        raceResults = pd.concat([raceResults,dfRace])

                        raceResults.to_pickle(f"../data/rawData/raceResults/{raceID}.pickle")

                    #receInfosに関する処理==========================================================================================================
                    if skip == False or os.path.isfile(f"../data/rawData/raceInfos/{raceID}.pickle") == False:
                        raceInfos = pd.DataFrame() #最終出力データセットの定義
                        text = soup.find("div",attrs={"class" : "data_intro"}).find_all("p")[0].text + soup.find("div",attrs={"class" : "data_intro"}).find_all("p")[1].text
                        info = re.findall("\w+",text)

                        infoDict = {}
                        infoDict["raceID"] = raceID
                        infoDict["raceName"] = soup.find("div",attrs={"class" : "data_intro"}).find_all("h1")[0].text
                        for text in info:
                            if text in ["芝","ダート"]:
                                infoDict["raceType"] = text
                            if "障" in text:
                                infoDict["raceType"] = "障害"
                            if "m" in text:
                                infoDict["course_len"] = re.findall("\d+",text)[0]
                            if text in ["良","稍重","重","不良"]:
                                infoDict["groundState"] = text
                            if text in ["曇","晴","雨","小雨","小雪","雪"]:
                                infoDict["weather"] = text
                            if "年" in text :
                                infoDict["date"] = text

                        raceInfos = pd.DataFrame(infoDict,index=[0])
                        #raceInfos = pd.concat([raceInfos, dfInfo], ignore_index=True)

                        raceInfos.to_pickle(f"../data/rawData/raceInfos/{raceID}.pickle")
                    
                    #returnTableに関する処理========================================================================================================
                    #同着の時にイレギュラーパターンがあるからそれを処理する機能の追加必須
                    if skip == False or os.path.isfile(f"../data/rawData/return/{raceID}.pickle") == False:
                        table1 = pd.read_html(StringIO(str(soup("table")[1]).replace("<br/>","or")))[0]
                        table2 = pd.read_html(StringIO(str(soup("table")[2]).replace("<br/>","or")))[0]
                        returnTable = pd.concat([table1,table2])
                        returnTable.reset_index(drop=True,inplace=True)
                        
                        betList = returnTable[0].unique()
                        for betting in betList:
                        #for rowNo in range(len(returnTable)):
                            tgt = returnTable[returnTable[0] == betting]
                            if "or" in tgt[1].to_string(index=False):        
                                for i in [1,2,3]:
                                    tgtstring = tgt[i].to_string(index=False)
                                    tgtlist = tgtstring.split("or")
                                    tgtdf = pd.DataFrame(tgtlist)
                                    tgtdf.rename(columns={0:i},inplace=True)
                                    if i == 1:
                                        returnFin = tgtdf
                                    else:
                                        returnFin = pd.merge(returnFin,tgtdf,left_index=True, right_index=True,how="left")

                                    returnFin[0] = betting

                                    returnTable = returnTable[returnTable[0] != betting]
                                    returnTable = pd.concat([returnTable,returnFin])

                        returnTable.reset_index(drop=True,inplace=True)
                        returnTable.rename(columns={0:"betting",1:"results",2:"payout",3:"popularity"},inplace=True)

                        returnTable["payout"] = returnTable["payout"].str.replace(",","").astype(int)
                        returnTable["payoutRate"] = returnTable["payout"] / 100
                        returnTable["raceID"] = raceID


                        returnTable.to_pickle(f"../data/rawData/return/{raceID}.pickle")

202501～202502のレース情報のデータを作成します。

makeYMList:   0%|          | 0/2 [00:00<?, ?it/s]

makeRaceDateURLList:   0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/18 [00:00<?, ?it/s]

20250105:   0%|          | 0/24 [00:00<?, ?it/s]

20250106:   0%|          | 0/24 [00:00<?, ?it/s]

20250111:   0%|          | 0/24 [00:00<?, ?it/s]

20250112:   0%|          | 0/24 [00:00<?, ?it/s]

20250113:   0%|          | 0/24 [00:00<?, ?it/s]

20250118:   0%|          | 0/24 [00:00<?, ?it/s]

20250119:   0%|          | 0/24 [00:00<?, ?it/s]

20250125:   0%|          | 0/36 [00:00<?, ?it/s]

20250126:   0%|          | 0/36 [00:00<?, ?it/s]

20250201:   0%|          | 0/36 [00:00<?, ?it/s]

20250202:   0%|          | 0/36 [00:00<?, ?it/s]

20250208:   0%|          | 0/24 [00:00<?, ?it/s]

20250209:   0%|          | 0/36 [00:00<?, ?it/s]

20250210:   0%|          | 0/12 [00:00<?, ?it/s]

20250215:   0%|          | 0/36 [00:00<?, ?it/s]

20250216:   0%|          | 0/36 [00:00<?, ?it/s]

20250222:   0%|          | 0/36 [00:00<?, ?it/s]

20250223:   0%|          | 0/36 [00:00<?, ?it/s]

  0%|          | 0/528 [00:00<?, ?it/s]

  0%|          | 0/528 [00:00<?, ?it/s]

In [ ]:
def makeRawDataRace(raceIDList,skip:bool = True):
    """
    html/raceに格納されているhtmlからレース結果/レース情報/払い戻し情報のrawデータを作成する関数
    """
    cnt = 1
    for raceID in raceIDList:
        if skip == False or os.path.isfile(f"../data/rawData/raceResults/{raceID}.pickle") == False or os.path.isfile(f"../data/rawData/raceInfos/{raceID}.pickle") == False or os.path.isfile(f"../data/rawData/return/{raceID}.pickle") == False:
            print(raceID)
            #共通処理======================================================================================================================
            with open(f"../data/html/race/{raceID}.txt","r") as f:
                html = f.read()

            soup = BeautifulSoup(html) #htmlをsoupオブジェクトへ
            
            #receResultsに関する処理=======================================================================================================
            if skip == False or os.path.isfile(f"../data/rawData/raceResults/{raceID}.pickle") == False:
                raceResults = pd.DataFrame() #最終出力データセットの定義
                try:
                    dfRace = pd.read_html(StringIO(str(soup("table")[0])))[0]
                except IndexError :
                    print(f"raceID:{raceID}の処理をスキップします。")
                    continue
                #dfRace = pd.read_html(StringIO(html))[0] #HTMLからレース結果を取得し、DataFrameへ

                dfRace["raceID"] = raceID

                horseIDList = []
                horseAList = soup.find("table",attrs={"summary":"レース結果"}).find_all("a",attrs={"href":re.compile("^/horse")})
                for a in horseAList:
                    horseID = re.findall("\d+",a["href"])
                    horseIDList.append(horseID[0])
                    
                dfRace["horseID"] = horseIDList

                jockeyIDList = []
                jockeyAList = soup.find("table",attrs={"summary":"レース結果"}).find_all("a",attrs={"href":re.compile("^/jockey")})
                for a in jockeyAList:
                    jockeyID = re.findall("\d+",a["href"])
                    jockeyIDList.append(jockeyID[0])

                dfRace["jockeyID"] = jockeyIDList

                raceResults = pd.concat([raceResults,dfRace])

                raceResults.to_pickle(f"../data/rawData/raceResults/{raceID}.pickle")

            #receInfosに関する処理==========================================================================================================
            if skip == False or os.path.isfile(f"../data/rawData/raceInfos/{raceID}.pickle") == False:
                raceInfos = pd.DataFrame() #最終出力データセットの定義
                text = soup.find("div",attrs={"class" : "data_intro"}).find_all("p")[0].text + soup.find("div",attrs={"class" : "data_intro"}).find_all("p")[1].text
                info = re.findall("\w+",text)

                infoDict = {}
                infoDict["raceID"] = raceID
                infoDict["raceName"] = soup.find("div",attrs={"class" : "data_intro"}).find_all("h1")[0].text
                for text in info:
                    if text in ["芝","ダート"]:
                        infoDict["raceType"] = text
                    if "障" in text:
                        infoDict["raceType"] = "障害"
                    if "m" in text:
                        infoDict["course_len"] = re.findall("\d+",text)[0]
                    if text in ["良","稍重","重","不良"]:
                        infoDict["groundState"] = text
                    if text in ["曇","晴","雨","小雨","小雪","雪"]:
                        infoDict["weather"] = text
                    if "年" in text :
                        infoDict["date"] = text

                raceInfos = pd.DataFrame(infoDict,index=[0])
                #raceInfos = pd.concat([raceInfos, dfInfo], ignore_index=True)

                raceInfos.to_pickle(f"../data/rawData/raceInfos/{raceID}.pickle")
            
            #returnTableに関する処理========================================================================================================
            #同着の時にイレギュラーパターンがあるからそれを処理する機能の追加必須
            if skip == False or os.path.isfile(f"../data/rawData/return/{raceID}.pickle") == False:
                #html2 = html.replace("<br />","or")
                #tables = pd.read_html(StringIO(html2))
                table1 = pd.read_html(str(soup("table")[1]).replace("<br/>","or"))[0]
                table2 = pd.read_html(str(soup("table")[2]).replace("<br/>","or"))[0]

                returnTable = pd.concat([table1,table2])
                returnTable.reset_index(drop=True,inplace=True)
                
                betList = returnTable[0].unique()
                for betting in betList:
                #for rowNo in range(len(returnTable)):
                    tgt = returnTable[returnTable[0] == betting]
                    if "or" in tgt[1].to_string(index=False):        
                        for i in [1,2,3]:
                            tgtstring = tgt[i].to_string(index=False)
                            tgtlist = tgtstring.split("or")
                            tgtdf = pd.DataFrame(tgtlist)
                            tgtdf.rename(columns={0:i},inplace=True)
                            if i == 1:
                                returnFin = tgtdf
                            else:
                                returnFin = pd.merge(returnFin,tgtdf,left_index=True, right_index=True,how="left")

                            returnFin[0] = betting

                            returnTable = returnTable[returnTable[0] != betting]
                            returnTable = pd.concat([returnTable,returnFin])

                returnTable.reset_index(drop=True,inplace=True)
                returnTable.rename(columns={0:"betting",1:"results",2:"payout",3:"popularity"},inplace=True)

                returnTable["payout"] = returnTable["payout"].str.replace(",","").astype(int)
                returnTable["payoutRate"] = returnTable["payout"] / 100
                returnTable["raceID"] = raceID


                returnTable.to_pickle(f"../data/rawData/return/{raceID}.pickle")

        cnt+=1      
    return

In [1]:
raceID="201201010506"

In [4]:
with open(f"../data/html/race/{raceID}.txt","r",encoding="shift-jis") as f:
    html = f.read()

soup = BeautifulSoup(html)

In [5]:
table1 = pd.read_html(StringIO(str(soup("table")[1]).replace("<br/>","or")))[0]
table2 = pd.read_html(StringIO(str(soup("table")[2]).replace("<br/>","or")))[0]
returnTable = pd.concat([table1,table2])
returnTable.reset_index(drop=True,inplace=True)

In [6]:
returnTable

     0                      1                    2           3
0   単勝                      9                 3740          10
1   複勝               9or3or16        680or160or510    10or1or8
2   枠連                  2 - 5                  800           3
3   馬連                  3 - 9                 5510          18
4  ワイド  3 - 9or9 - 16or3 - 16  1,670or6,250or1,040  18or59or10
5   馬単                  9 → 3                12100          41
6  三連複             3 - 9 - 16                23210          79
7  三連単             9 → 3 → 16               173940         505

In [7]:
betList = returnTable[0].unique()
for betting in betList:
    tgt = returnTable[returnTable[0] == betting]
    if "or" in tgt[1].to_string(index=False):        
        for i in [1,2,3]:
            tgtstring = tgt[i].to_string(index=False)
            tgtlist = tgtstring.split("or")
            tgtdf = pd.DataFrame(tgtlist)
            tgtdf.rename(columns={0:i},inplace=True)
            if i == 1:
                returnFin = tgtdf
            else:
                returnFin = pd.merge(returnFin,tgtdf,left_index=True, right_index=True,how="left")

            returnFin[0] = betting

            returnTable = returnTable[returnTable[0] != betting]
            returnTable = pd.concat([returnTable,returnFin])

In [8]:
returnTable

     0           1       2    3
0   単勝           9    3740   10
2   枠連       2 - 5     800    3
3   馬連       3 - 9    5510   18
5   馬単       9 → 3   12100   41
6  三連複  3 - 9 - 16   23210   79
7  三連単  9 → 3 → 16  173940  505
0   複勝           9     680   10
1   複勝           3     160    1
2   複勝          16     510    8
0  ワイド       3 - 9   1,670   18
1  ワイド      9 - 16   6,250   59
2  ワイド      3 - 16   1,040   10

In [9]:
returnTable.reset_index(drop=True,inplace=True)
returnTable.rename(columns={0:"betting",1:"results",2:"payout",3:"popularity"},inplace=True)

In [16]:
returnTable["payout"] = returnTable["payout"].apply(lambda x: int(str(x).replace(",", "")))

In [19]:
returnTable

   betting     results  payout popularity  payoutRate
0       単勝           9    3740         10        37.4
1       枠連       2 - 5     800          3         8.0
2       馬連       3 - 9    5510         18        55.1
3       馬単       9 → 3   12100         41       121.0
4      三連複  3 - 9 - 16   23210         79       232.1
5      三連単  9 → 3 → 16  173940        505      1739.4
6       複勝           9     680         10         6.8
7       複勝           3     160          1         1.6
8       複勝          16     510          8         5.1
9      ワイド       3 - 9    1670         18        16.7
10     ワイド      9 - 16    6250         59        62.5
11     ワイド      3 - 16    1040         10        10.4

In [18]:
returnTable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   betting     12 non-null     object
 1   results     12 non-null     object
 2   payout      12 non-null     int64
 3   popularity  12 non-null     object
 4   payoutRate  12 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 608.0+ bytes

In [17]:
returnTable["payoutRate"] = returnTable["payout"] / 100

In [ ]:
returnTable["raceID"] = raceID

In [3]:
forHRD = makeRaceData("202501","202501")
forHRD.makeYMList()
forHRD.makeRaceDateURLList()
forHRD.makeRaceURLList()

2025/01～2025/01のレース情報のデータを作成します。

makeYMList:   0%|          | 0/1 [00:00<?, ?it/s]

makeYMList: 100%|██████████| 1/1 [00:00<?, ?it/s]
makeRaceDateURLList: 100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
makeRaceURLList: 100%|██████████| 9/9 [01:08<00:00,  7.66s/it, date=2025/01/26]

In [2]:
files = glob.glob("../data/html/ped/*")
print(f"対象頭数:{len(files)}")

対象頭数:40826

In [4]:
def makehorseIDList(files):
    """
    に指定されたレース結果からユニークなhorseIDのリストを作成する
    """
    horseIDList = []

    cnt = 1
    for file in files:
        print("\r" + f"horseIDListの作成中({cnt}/{len(files)})",end="")
        filename = str(file.split("/")[-1:])
        raceID = re.sub(r"\D+", "", filename)

        horseIDTmp = pd.read_pickle(f"../data/rawData/raceResults/{raceID}.pickle")
        horseIDTmp2 = horseIDTmp["horseID"].unique()
        horseIDList.extend(horseIDTmp2)
        cnt+=1
    
    horseIDListDF = pd.DataFrame(horseIDList)
    horseIDListFin = horseIDListDF[0].unique()

    print("\n" + f"{len(horseIDListFin)}頭分のhorseIDListを作成しました")
    return horseIDListFin

In [7]:
horseIDListPrep = []
for raceID in forHRD.raceIDList:
    raceResultsDF = pd.read_pickle(f"../data/rawData/raceResults/{raceID}.pickle")
    horseIDTmp = raceResultsDF["horseID"].unique()
    horseIDListPrep.extend(horseIDTmp)

horseIDList = pd.DataFrame(horseIDListPrep)[0].unique().tolist()

In [8]:
horseIDList[0:3]

['2022105247', '2022106581', '2022107050']

In [ ]:
horseIDList = pd.DataFrame(horseIDListPrep)[0].unique().tolist()

In [ ]:
from makeRawData import makeRaceData,makeHorseData
import pandas as pd

In [2]:
horseIDList = ['2022105247', '2022106581', '2022107050']

In [3]:
MHD = makeHorseData(horseIDList)
MHD.getHorseHTML(skipResult=False, skipPED=False)
MHD.makeHorseRawData(skipResult=False, skipPED=False)

getHorseHTML: 100%|██████████| 3/3 [00:12<00:00,  4.28s/it, horseID=2022107050(血統表)]
makeHorseRawData: 100%|██████████| 3/3 [00:01<00:00,  2.37it/s, horseID=2022107050(血統情報)]

#馬の

In [3]:
files = glob.glob("../data/rawData/raceResults/*")
print(f"{len(files)}レース分の結果ファイルのリストを作成しました")

52341レース分の結果ファイルのリストを作成しました

In [10]:
import re
import pandas as pd
import glob

In [15]:
def makehorseIDList(files):
    """
    filesに指定されたレース結果からユニークなhorseIDのリストを作成する
    """
    horseIDList = []

    cnt = 1
    for file in files:
        print("\r" + f"horseIDListの作成中({cnt}/{len(files)})",end="")
        filename = str(file.split("/")[-1:])
        raceID = re.sub(r"\D+", "", filename)

        horseIDTmp = pd.read_pickle(f"../data/rawData/raceResults/{raceID}.pickle")
        horseIDTmp2 = horseIDTmp["horseID"].unique()
        horseIDList.extend(horseIDTmp2)
        cnt+=1
    
    horseIDListDF = pd.DataFrame(horseIDList)
    horseIDListFin = horseIDListDF[0].unique().tolist()

    print("\n" + f"{len(horseIDListFin)}頭分のhorseIDListを作成しました")
    return horseIDListFin

In [16]:
horseIDList = makehorseIDList(files)

horseIDListの作成中(52341/52341)
78112頭分のhorseIDListを作成しました

In [21]:
from bs4 import BeautifulSoup

In [39]:
horseID = "2006106019"

In [42]:
with open(f"../data/html/horse/{horseID}.txt","r",encoding="shift-jis") as f: #ファイルを開く
    html = f.read()

In [43]:
html

'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja" id="html">\n<head>\n\n<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n<meta http-equiv="content-type" content="text/html; charset=euc-jp" />\n<meta http-equiv="content-script-type" content="text/javascript" />\n<meta http-equiv="content-style-type" content="text/css" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/reset.css?20160421" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/common.css?20210819" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/db_detail.css?20180621" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/horse_detail.css?20250620" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/win.css?20160421" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/db_top.css?20160421" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/prettyPhoto.css?20160421" rel="stylesheet" type="text/css" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/jquery.fancybox-1.3.4.css?20160421" rel="stylesheet" type="text/css" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/db_classic_nk01.css?201911209" rel="stylesheet" type="text/css" />\n<!-- link rel="stylesheet" href="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/css/common_header.css" type="text/css" -->\n<script language="javascript">\n<!--\nb = navigator.userAgent.toUpperCase();\nif(b.indexOf("MAC") >= 0)\n{\ncssFile = "mac.css";\n}\nelse\n{\ncssFile = "win.css";\n}\ndocument.write("<link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.netkeiba.com/img.db/common/css/" + cssFile + "\'>");\n// -->\n</script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery-1.8.2.min.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.cookie.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/fontsize.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.prettyPhoto.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.fieldtag.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/table_hover.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.fancybox-1.3.4.pack.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.easing-1.3.pack.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.carouFredSel-6.2.0-packed.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.touchSwipe.min.js?20160421"></script>\n<link rel="stylesheet" type="text/css" href="https://cdn.netkeiba.com/img.db/common/css/ajaxtabs.css?20160421" />\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/ajaxtabs.js?20160421">\n/***********************************************\n* Ajax Tabs Content script v2.2- c Dynamic Drive DHTML code library (www.dynamicdrive.com)\n* This notice MUST stay intact for legal use\n* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code\n***********************************************/\n</script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/get_ad_request.js"></script>\n<script type="text/javascript">\n<!--\nvar _user_action_api_url    = \'https://cdn.netkeiba.com/img.user\';\nvar _newsapi_action_api_url = \'https://cdn.netkeiba.com/img.newsapi/\';\nvar _social_action_api_url  = \'https://db.netkeiba.com/v1.1/\';\nvar _bbs_action_api_url     = \'https://bbs.netkeiba.com/\';\n// -->\n</script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.user/common/js/user.action.js?2016042101"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.newsapi//common/js/newsapi.action.js?2016042101"></script>\n<script type="text/javascript" src="https://db.netkeiba.com/v1.1//common/js/social.action.js"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.bbs/common/js/bbs.action.js?2018053101"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.regist.sp//common/js/monthly_goods_link.js?2017080201"></script>\n\n<meta http-equiv="content-language" content="ja">\n<meta name="viewport" content="width=device-960px">\n<meta name="format-detection" content="telephone=no" />\n<meta name="description" content="ビービーボルト (B B Bolt)の競走馬データです。競走成績、血統情報、産駒情報などをはじめ、50万頭以上の競走馬・騎手・調教師・馬主・生産者・レースの全データがご覧いただけます。" />\n<meta name="keywords" content="競馬情報,競走馬,騎手,レース,調教師,馬主,検索,データベース,JRA,netkeiba,ネット競馬" />\n<meta name="thumbnail" content="https://cdn.netkeiba.com/img.db.sp/show_photo.php?horse_id=2006106019&no=spdb&tn=&tmp=no&default_image=netkeiba" />\n<!-- ogp用 -->\n<meta property="og:site_name" content="netkeiba" />\n<meta property="og:type" content="article" />\n<meta property="og:title" content="ビービーボルト (B B Bolt) | 競走馬データ - netkeiba" />\n<meta property="og:url" content="https://db.netkeiba.com/horse/2006106019/" />\n<meta property="og:description" content="ビービーボルト (B B Bolt)の競走馬データです。競走成績、血統情報、産駒情報などをはじめ、50万頭以上の競走馬、騎手・調教師・馬主・生産者の全データがご覧いただけます。" />\n<meta property="og:image" content="https://cdn.netkeiba.com/img.db.sp/show_photo.php?horse_id=2006106019&no=spdb&tn=&tmp=no&default_image=netkeiba" />\n<!-- Twitter用 -->\n<meta property="twitter:card" content="summary_large_image">\n<meta property="twitter:site" content="@netkeiba">\n<!-- Facebook用 -->\n<meta property="fb:admins" content="30367" />\n<!-- アノテーション -->\n<link rel="canonical" href="https://db.netkeiba.com/horse/2006106019/" />\n<link rel="alternate" media="only screen and (max-width: 640px)" href="https://db.sp.netkeiba.com/horse/2006106019/" />\n<link rel="alternate" href="https://db.netkeiba.com/horse/2006106019/"  hreflang="ja" />\n<link rel="alternate" href="https://db.netkeiba.com/horse/2006106019/"  hreflang="x-default" />\n<link rel="alternate" href="https://en.netkeiba.com/db/horse/2006106019/" hreflang="en" />\n<link rel="alternate" type="application/rss+xml" href="https://rss.netkeiba.com/?pid=rss_netkeiba&site=netkeiba" />\n<link rel="apple-touch-icon" href="https://cdn.netkeiba.com/img.sp/common/img/common/icon_home.png" />\n<title>ビービーボルト (B B Bolt) | 競走馬データ - netkeiba</title>\n\n\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/tab_change_jquer.js"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.select.js"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.MetaData.js"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.colorbox.js?20180321"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/slick.js"></script>\n<link rel="stylesheet" href="https://cdn.netkeiba.com/img.db/common/css/colorbox.css?20180321" type="text/css" media="screen">\n<link rel="stylesheet" href="https://cdn.netkeiba.com/img.db/common/css/slick.css?20200928" type="text/css" media="screen">\n<link rel="stylesheet" href="https://cdn.netkeiba.com/img.db/common/css/paddock.css?20230601" type="text/css" media="all" />\n\n\n\n<script type="text/javascript">\nwindow._taboola = window._taboola || [];\n_taboola.push({article:\'auto\'});\n!function (e, f, u, i) {\nif (!document.getElementById(i)){\ne.async = 1;\ne.src = u;\ne.id = i;\nf.parentNode.insertBefore(e, f);\n}\n}(document.createElement(\'script\'),\ndocument.getElementsByTagName(\'script\')[0],\n\'//cdn.taboola.com/libtrc/netkeiba/loader.js\',\n\'tb_loader_script\');\nif(window.performance && typeof window.performance.mark == \'function\')\n{window.performance.mark(\'tbl_ic\');}\n</script>\n\n\n<!-- Google Tag Manager -->\n<script>\nwindow.dataLayer = window.dataLayer || [];\ndataLayer.push({\n\'itemInfo\': \'\',\'memberRank\': \'NotLogin\',\'memberId\': \'\'\n});\n</script>\n\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'//www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-K6PJT6\');</script>\n<!-- End Google Tag Manager -->\n</head>\n<body class="db " id="horse_detail">\n<noscript>\nお客様のブラウザはジャバスクリプト（JavaScript）に対応していないか無効になっています。\n</noscript>\n<div id="page">\n\n<link rel="stylesheet" href="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/css/pc_header.css?20241225" type="text/css" media="screen" />\n<style>\n* {\nmargin: 0;\npadding: 0;\nfont-size: 100%;\n/*vertical-align: baseline;*/\ntext-shadow: none;\n-webkit-text-size-adjust: none !important;\noutline: none;\n}\nheader .Header_Inner {\nwidth: unset;\n}\nheader .Header_Inner .SiteToggleBtn01 a {\nmin-width: unset;\n}\n</style>\n<p class="sp_nk_btn disp_none"><a href="http://www.netkeiba.com/?pid=go_sp" title="スマートフォン版へ"><img src="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/image/sp_nk_link_02.png" alt="スマートフォン版へ" class="imgover" /></a></p>\n<header class="Header_Area fc">\n<div class="Header_Inner fc">\n<h1>\n<a href="https://www.netkeiba.com/?rf=logo" title="netkeiba">\n<img src="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/image/common/netkeiba_logo02.png?20231003" alt="netkeiba">\n</a>\n</h1>\n<div class="DB_Search_Input">\n<form class="Search_Box" action="https://www.netkeiba.com/" method="POST">\n<input type="hidden" name="pid" value="search">\n<input type="hidden" name="type" value="db">\n<div class="InputTxt_Form_Box">\n<input class="Txt_Form" placeholder="馬名で検索" value="" type="text" name="word" id="keywords">\n</div><!-- / .InputTxt_Form -->\n<div class="Submit_Btn_Box">\n<svg xmlns="http://www.w3.org/2000/svg" width="41.05" height="41.05" viewBox="0 0 41.05 41.05" class="IconInput01">\n<g id="icon_search" transform="translate(-234.6 -459.7)">\n<circle cx="15.6" cy="15.6" r="15.6" transform="translate(236.1 461.2)" class="st0"/>\n<g>\n<path d="M275.2,498.2a1.335,1.335,0,0,1,0,2l-.1.1a1.335,1.335,0,0,1-2,0l-11.2-11.2a1.335,1.335,0,0,1,0-2l.1-.1a1.335,1.335,0,0,1,2,0Z" class="st1"/>\n</g>\n</g>\n</svg>\n<input class="Submit_Btn" type="submit" name="submit" value="検 索">\n</div><!-- / .Submit_Btn_Box -->\n</form>\n</div><!-- / .DB_Search_Input -->\n<div class="MyMenuWrap">\n<ul class="UserMyMenu fc">\n\n<li>\n<a href="https://regist.netkeiba.com/?pid=premium&rf=header">\n<span>プレミアムサービス</span>\n</a>\n</li>\n<li>\n<a href="https://race.netkeiba.com/bookmark/bookmark.html?rf=navi" class="Icon_Header Icon_MyfavHorse">\n<span>お気に入り馬</span>\n</a>\n</li>\n<li>\n<a href="https://race.netkeiba.com/notes/schedule.html?rf=navi" class="Icon_Header Icon_Note">\n<span>メモ</span>\n</a>\n</li>\n<li>\n<a href="https://regist.netkeiba.com/account/?pid=login" class="Icon_Header Icon_Login">\n<span>ログイン/会員登録</span>\n</a>\n</li>\n<li class="disp_none header_stage_area no_login_show">\n<a href="https://regist.netkeiba.com/?pid=stage_login&action=login&return_url=https://regist.netkeiba.com/">\n<span>(s)ログイン</span>\n</a>\n</li>\n<li class="disp_none header_stage_area no_login_show">\n<a href="https://regist.netkeiba.com/?pid=user_add_form&payment=nk_user&goods_cd=310409&opt=init">\n<span>(s)無料会員登録</span>\n</a>\n<li class="disp_none header_stage_area login_show">\n<a href="https://regist.netkeiba.com/?pid=stage_login&action=logout&return_url=https://regist.netkeiba.com/">\n<span>(s)ログアウト</span>\n</a>\n</li>\n</ul>\n<div class="SiteToggleBtn01 Keirin">\n<a href="https://keirin.netkeiba.com/?rf=nk_pc_header">\n<span class="LiveRace">LIVE</span>\n<img src="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/image/common/icon_keirin01.png" alt="" width="21" height="16" class="KeirinLogoMark01">競輪\n</a>\n</div><!-- /.SiteToggleBtn01 -->\n</div>\n</div><!-- /.Header_Inner -->\n</header>\n<nav class="ContentNavi01">\n<ul class="fc">\n<li class="Top">\n<a href="https://www.netkeiba.com/?rf=navi" title="トップ" id="navi_link_top">トップ</a>\n</li>\n<li class="News">\n<a href="https://news.netkeiba.com/?rf=navi" title="ニュース" id="navi_link_news">ニュース</a>\n</li>\n<li class="Race">\n<a href="https://race.netkeiba.com/top/?rf=navi" title="レース" id="navi_link_race">レース</a>\n</li>\n<li class="AI New">\n<a href="https://race.netkeiba.com/AI/AI.html?rf=navi" title="AI" id="navi_link_AI">A I</a>\n</li>\n<!-- <li class="Special">\n<a href="https://race.netkeiba.com/special/index.html?id=0059&rf=navi" title="日本ダービー" id="navi_link_Special">日本ダービー</a>\n</li> -->\n<li class="Yoso">\n<a href="https://yoso.netkeiba.com/?access=init&rf=navi" title="予想" id="navi_link_yoso">予想</a>\n</li>\n<li class="Builder New">\n<a href="https://builder.netkeiba.com/?rf=navi" title="UMAIビルダー" id="navi_link_builder">UMAIビルダー</a>\n</li>\n<li class="Column">\n<a href="https://news.netkeiba.com/?pid=column_top&rf=navi" title="コラム" id="navi_link_column">コラム</a>\n</li>\n<li class="Tv">\n<a href="https://tv.netkeiba.com/?rf=navi" title="netkeibaTV" id="navi_link_tv">netkeibaTV</a>\n</li>\n<li class="Local">\n<a href="https://nar.netkeiba.com/top/?rf=navi" title="地方競馬" id="navi_link_nar">地方競馬</a>\n</li>\n<li class="Db">\n<a href="https://db.netkeiba.com/?rf=navi" title="データベース" id="navi_link_db">データベース</a>\n</li>\n<li class="Shop New">\n<a href="https://shop.netkeiba.com/?utm_source=netkeiba&utm_medium=+referral&utm_campaign=pcgnavi_20240425" title="ショップ" id="navi_link_shop" target="_blank">ショップ</a>\n</li>\n<li class="Paper">\n<a href="https://yoso.netkeiba.com/senmonshi/?rf=navi" title="競馬新聞" id="navi_link_senmonshi">競馬新聞</a>\n</li>\n<li class="YosoCS">\n<a href="https://orepro.netkeiba.com/?rf=navi" title="俺プロ" id="navi_link_orepro">俺プロ</a>\n</li>\n<li class="Owner">\n<a href="https://owner.netkeiba.com/?rf=navi" title="一口馬主" id="navi_link_owner">一口馬主</a>\n</li>\n<li class="Pog">\n<a href="https://pog.netkeiba.com/?rf=navi" title="POG" id="navi_link_pog">POG</a>\n</li>\n<li class="Matome">\n<a href="https://dir.netkeiba.com/keibamatome/index.html?rf=navi" title="まとめ" id="navi_link_keibamatome">まとめ</a>\n</li>\n</ul>\n</nav><!-- /.ContentNavi01 -->\n<!-- Geniee Wrapper Head Tag -->\n<script>\nwindow.gnshbrequest = window.gnshbrequest || {cmd:[]};\ngnshbrequest.cmd.push(function(){\ngnshbrequest.registerPassback("1491447");\ngnshbrequest.registerPassback("1491448");\ngnshbrequest.registerPassback("1492793");\ngnshbrequest.registerPassback("1491462_1");\ngnshbrequest.forceInternalRequest();\n});\n</script>\n<script async src="https://cpt.geniee.jp/hb/v1/211239/47/wrapper.min.js"></script>\n<!-- /Geniee Wrapper Head Tag -->\n<script async src="https://cdn.netkeiba.com/img.racev4.sp/common/js/nd_util.min.js"></script>\n<script type="text/javascript">\n$(document).ready(function() {\nshow_user();\n});\nfunction show_user(){\nvar is_stage = \'\';\nvar is_user  = \'\';\nvar is_alert = \'\';\nvar is_sp    = \'\';\nvar nickname = \'\';\nvar user_img = \'\';\nif(is_sp) {\n$(\'.sp_nk_btn\').show();\n}\nif(! is_stage) {\n$(\'.header_stage_area\').remove();\n}\nif(is_user){\n//ログイン中\n$(\'.login_show\').show();\nif(is_alert) {\n$(\'.Alert_New\').show();\n}\n} else {\n//未ログイン\n$(\'.no_login_show\').show();\n$(\'.login_show\').remove();\n}\n}\n</script>\n\n<div class="genre_menu fc">\n<ul>\n<li ><a href="/" title="競馬データTOP">競馬データTOP</a></li>\n<li class="active"><a href="/?pid=horse_top" title="競走馬">競走馬</a></li>\n<li ><a href="/?pid=jockey_top" title="騎手">騎手</a></li>\n<li ><a href="/?pid=trainer_top" title="調教師">調教師</a></li>\n<li ><a href="/?pid=owner_top" title="馬主">馬主</a></li>\n<li ><a href="/?pid=breeder_top" title="生産者">生産者</a></li>\n<li ><a href="/?pid=race_top" title="レース">レース</a></li>\n<li ><a href="/?pid=classic_index" title="クラシック">クラシック</a></li>\n<li ><a href="https://db.sp.netkeiba.com/winner_search/home" title="勝ち馬サーチ">勝ち馬サーチ</a></li>\n</ul>\n</div><!-- /.genre_menu -->\n<div id="contents" class="fc">\n\n<style>\n.add_bnr{\nmargin:20px 0 10px;\ntext-align: center;\n}\n.add_bnr a{\ndisplay: inline-block;\n}\n</style>\n<div class="add_bnr">\n\n<div id="pc_nk_db_horse1st"></div>\n<script language="JavaScript" type="text/javascript">\n//noCacheParam=Math.random()*10000000000;document.write(\'<scr\'+\'ipt type="text/javascript" src="https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=pc_nk_db_horse1st&isJS=true&encoding=EUC-JP&ord=\' + noCacheParam + \'"></scr\'+\'ipt>\');\nif ($(\'#pc_nk_db_horse1st\').html().length<1){\n$.ajax(\'https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=pc_nk_db_horse1st\', {\ntimeout : 10000, /* 10000 ms */\n}).then(function(data) { $("#pc_nk_db_horse1st").html(data)} )\n}\n</script>\n</div>\n<div class="top_newinfo_box fc">\n<dl>\n<dd>\n<div style="line-height: 1.8em;">\n<a href="https://info.netkeiba.com/?pid=info_detail&id=1183" target="_blank" title="netkeirin"><img src="https://cdn.netkeiba.com/img.db/common/image/mark_arrow_red_01.gif" border="0" style="display:inline"><span style="text-indent:4px">コミュニティ健全化に向けた取り組みについて</span></a>\n</div>\n<div style="line-height: 1.8em;">\n<a href="//keirin.netkeiba.com/?rf=nk_pc_dbhorse" target="_blank" title="netkeirin"><img src="https://cdn.netkeiba.com/img.db/common/image/mark_arrow_blue_01.gif" border="0" style="display:inline"><span style="text-indent:4px">いま競輪が熱い！ netkeirinで競輪を気軽に楽しもう</span></a>\n</div>\n<div style="line-height: 1.8em;">\n<!-- <a href="//keirin.netkeiba.com/?rf=nk_pc_dbhorse" target="_blank" title="netkeirin"><img src="https://cdn.netkeiba.com/img.db/common/image/mark_arrow_blue_01.gif" border="0" style="display:inline"><span style="text-indent:4px">なぞのテキストリンク1</span></a> -->\n<!-- new_db_text1 ad start  -->\n<div id="new_db_text1"></div>\n<script language="JavaScript" type="text/javascript">\nif ($(\'#new_db_text1\').html().length<1){\n$.ajax(\'https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text1\', {\ntimeout : 10000, /* 10000 ms */\n}).then(function(data) { $("#new_db_text1").html(data)} )\n}\n//noCacheParam=Math.random()*10000000000;\n//document.write(\'<scr\'+\'ipt type="text/javascript" src="https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text1&isJS=true&encoding=EUC-JP&ord=\' + noCacheParam + \'"></scr\'+\'ipt>\');\n</script><!--noscript><iframe marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" bordercolor="#000000" width="700" height="20" src="https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text1&encoding=EUC-JP"></iframe></noscript-->\n<!-- new_db_text1 ad end  -->\n</div>\n<div style="line-height: 1.8em;">\n<!-- <a href="//keirin.netkeiba.com/?rf=nk_pc_dbhorse" target="_blank" title="netkeirin"><img src="https://cdn.netkeiba.com/img.db/common/image/mark_arrow_blue_01.gif" border="0" style="display:inline"><span style="text-indent:4px">なぞのテキストリンク2</span></a> -->\n<!-- new_db_text2 ad start  -->\n<div id="new_db_text2"></div>\n<script language="JavaScript" type="text/javascript">\nif ($(\'#new_db_text2\').html().length<1){\n$.ajax(\'https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text2\', {\ntimeout : 10000, /* 10000 ms */\n}).then(function(data) { $("#new_db_text2").html(data)} )\n}\n//noCacheParam=Math.random()*10000000000;\n//document.write(\'<scr\'+\'ipt type="text/javas

In [25]:
with open(f"../data/html/ped/{horseID}.txt","r",encoding="utf-8") as f: #ファイルを開く
    html = f.read()

In [44]:
soup = BeautifulSoup(html,"html.parser")

In [45]:
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nビービーボルト (B B Bolt) | 競走馬データ - netkeiba\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nお客様のブラウザはジャバスクリプト（JavaScript）に対応していないか無効になっています。\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nプレミアムサービス\n\n\n\n\nお気に入り馬\n\n\n\n\nメモ\n\n\n\n\nログイン/会員登録\n\n\n\n\n(s)ログイン\n\n\n\n\n(s)無料会員登録\n\n\n\n(s)ログアウト\n\n\n\n\n\nLIVE\n競輪\n\n\n\n\n\n\n\n\nトップ\n\n\nニュース\n\n\nレース\n\n\nA I\n\n\n\n予想\n\n\nUMAIビルダー\n\n\nコラム\n\n\nnetkeibaTV\n\n\n地方競馬\n\n\nデータベース\n\n\nショップ\n\n\n競馬新聞\n\n\n俺プロ\n\n\n一口馬主\n\n\nPOG\n\n\nまとめ\n\n\n\n\n\n\n\n\n\n\n\n競馬データTOP\n競走馬\n騎手\n調教師\n馬主\n生産者\nレース\nクラシック\n勝ち馬サーチ\n\n\n\n\n\n\n\n\n\n\n\n\nコミュニティ健全化に向けた取り組みについて\n\n\nいま競輪が熱い！ netkeirinで競輪を気軽に楽しもう\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nビービーボルト\n\nB B Bolt\n\n抹消\u3000セ\u3000鹿毛 \n\n\n共有\n\n\n\n\n\n\nお気に入り馬登録\n\n\n\n0人\n\n\n\nシェアする\n\n\n\n\n\nX\n\n\n\n\n\nFacebook\n\n\n\n\n\nLINE\n\n\n\n\n\nURLをコピー\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTOP\n\n\n戦績\n\n\n血統\n\n\n掲示板\n\n\n写真\n\n\nメモ\n\n\n調教\n\n\n短評\n\n\nコメント\n\n\nパドック映像\n\n\nフォトパドック\n\n\n\n近況\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n«\n»\n\n写真一覧 / 写真投稿\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n生年月日\n2006年3月18日\n\n\n調教師\n高橋祥泰 (美浦)\n\n\n馬主\n坂東牧場\n\n\n生産者\n碧雲牧場\n\n\n産地\n日高町\n\n\nセリ取引価格\n\n-\n\n\n\n獲得賞金 (中央)\n\n\n464万円\n\n\n\n獲得賞金 (地方)\n\n\n42万円\n\n\n\n通算成績\n32戦2勝 [2-1-0-29]\n\n\n主な勝鞍\nD1 ー1組\n\n\n近親馬\nオースミゲンカイ、ビービーディケイド\n\n\n\n\n\n\n血統\n血統詳細・兄弟馬\n\n\n\n\n\n\nタニノギムレット\n\n\nブライアンズタイム\n\n\n\n\nタニノクリスタル\n\n\n\n\nオースミアモール\n\n\nサクラバクシンオー\n\n\n\n\nオースミメリー\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n掲示板 (件)\n\n投稿する\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nビービーボルトの競走成績\n\nスマホでもこの馬のデータをチェック！\n\n\n\n\n\n\n日付\n開催\n天気\nR\nレース名\n映像\n頭数\n枠番\n馬番\nオッズ\n人気\n着順\n騎手\n斤量\n距離\n馬場\n馬場指数\nタイム\n着差\nﾀｲﾑ指数\n通過\nペース\n上り\n馬体重\n厩舎ｺﾒﾝﾄ\n備考\n勝ち馬(2着馬)\n賞金\n\n\n\n\n2012/10/18\n園田\n曇\n12\nひがんばな賞B1B2\n\n\n\xa0\n\n\n12\n6\n8\n250.5\n12\n11\n\n瀬沢宙\n\n55\nダ1230\n不\n\n\n\n\xa0\n\n1:21.1\n3.4\n\n\n\n\xa0\n\n12-12-12-11\n\xa0\n38.9\n511(+1)\n\n\n\xa0\n\n\n\n\n\xa0\n\nリアリーサムシング\n\xa0\n\n2012/09/21\n園田\n晴\n8\nB2二\u30003歳以上\n\n\n\xa0\n\n\n9\n2\n2\n53.2\n6\n9\n\n三野孝徳\n\n56\nダ1400\n稍\n\n\n\n\xa0\n\n1:36.0\n4.8\n\n\n\n\xa0\n\n8-8-8-8\n\xa0\n42.2\n510(+2)\n\n\n\xa0\n\n\n\n\n\xa0\n\nベストファッション\n\xa0\n\n2012/08/29\n門別\n曇\n11\n門別ライオンズクラブ\n\n\n\xa0\n\n\n12\n7\n10\n99.5\n11\n10\n\n桑村真明\n\n56\nダ1200\n良\n\n\n\n\xa0\n\n1:17.8\n2.1\n\n\n\n\xa0\n\n9-10\n\xa0\n40.6\n508(0)\n\n\n\xa0\n\n\n\n\n\xa0\n\nニットウエジョン\n\xa0\n\n2012/08/22\n門別\n晴\n10\nアンタレス特別\n\n\n\xa0\n\n\n11\n4\n4\n372.6\n11\n11\n\n桜井拓章\n\n54\nダ1200\n良\n\n\n\n\xa0\n\n1:17.4\n3.1\n\n\n\n\xa0\n\n11-11\n\xa0\n40.5\n508(0)\n\n\n\xa0\n\n\n\n\n\xa0\n\nグレンチェック\n\xa0\n\n2012/08/14\n門別\n晴\n12\nK’sガーデン特別\n\n\n\xa0\n\n\n8\n8\n8\n58.8\n8\n8\n\n桜井拓章\n\n55\nダ1800\n重\n\n\n\n\xa0\n\n2:00.8\n5.2\n\n\n\n\xa0\n\n7-7-8-8\n\xa0\n41.0\n508(-8)\n\n\n\xa0\n\n\n\n\n\xa0\n\nアグネスフォーカス\n\xa0\n\n2012/08/08\n門別\n曇\n10\nレダ特別\n\n\n\xa0\n\n\n10\n5\n5\n128.9\n10\n10\n\n桜井拓章\n\n54\nダ1800\n良\n\n\n\n\xa0\n\n2:07.8\n10.4\n\n\n\n\xa0\n\n4-4-10-10\n\xa0\n47.9\n516(+8)\n\n\n\xa0\n\n\n\n\n\xa0\n\nシルバーブリオン\n\xa0\n\n2012/08/01\n門別\n曇\n11\n様似町アポイの火まつ\n\n\n\xa0\n\n\n11\n7\n9\n202.4\n10\n11\n\n桜井拓章\n\n56\nダ1200\n良\n\n\n\n\xa0\n\n1:18.1\n3.3\n\n\n\n\xa0\n\n7-8\n\xa0\n40.3\n508(-4)\n\n\n\xa0\n\n\n\n\n\xa0\n\nスパイア\n\xa0\n\n2012/07/25\n門別\n曇\n5\nC1\u3000ー2組\n\n\n\xa0\n\n\n8\n2\n2\n65.5\n6\n6\n\n桑村真明\n\n56\nダ1200\n良\n\n\n\n\xa0\n\n1:17.8\n2.2\n\n\n\n\xa0\n\n6-6\n\xa0\n40.2\n512(+4)\n\n\n\xa0\n\n\n\n\n\xa0\n\nボスビアー\n\xa0\n\n2012/07/18\n門別\n晴\n11\nHOKKAIDO競馬\n\n\n\xa0\n\n\n10\n7\n7\n154.1\n9\n10\n\n桑村真明\n\n56\nダ1200\n良\n\n\n\n\xa0\n\n1:17.8\n2.4\n\n\n\n\xa0\n\n8-8\n\xa0\n40.6\n508(-2)\n\n\n\xa0\n\n\n\n\n\xa0\n\nマイイブキ\n\xa0\n\n2012/07/03\n門別\n晴\n11\n雪印種苗スノービルダ\n\n\n\xa0\n\n\n9\n6\n6\n205.2\n8\n8\n\n桑村真明\n\n56\nダ1200\n良\n\n\n\n\xa0\n\n1:15.9\n1.7\n\n\n\n\xa0\n\n7-6\n\xa0\n39.3\n510(-6)\n\n\n\xa0\n\n\n\n\n\xa0\n\nチューリングマシン\n\xa0\n\n2012/06/19\n門別\n曇\n11\n花菖蒲特別\n\n\n\xa0\n\n\n11\n5\n5\n72.3\n9\n9\n\n山口竜一\n\n56\nダ1200\n稍\n\n\n\n\xa0\n\n1:16.6\n1.8\n\n\n\n\xa0\n\n9-10\n\xa0\n39.9\n516(+6)\n\n\n\xa0\n\n\n\n\n\xa0\n\nボスビアー\n\xa0\n\n2012/06/14\n門別\n晴\n10\nミザール特別\n\n\n\xa0\n\n\n11\n5\n5\n258.8\n11\n10\n\n佐々木国\n\n54\nダ1800\n良\n\n\n\n\xa0\n\n1:59.5\n3.5\n\n\n\n\xa0\n\n5-5-6-9\n\xa0\n41.9\n510(0)\n\n\n\xa0\n\n\n\n\n\xa0\n\nキンショーオーロラ\n\xa0\n\n2012/06/05\n門別\n晴\n10\n手稲山ミヤマスミレ特\n\n\n\xa0\n\n\n11\n6\n6\n50.1\n7\n10\n\n阿部龍\n\n56\nダ1200\n良\n\n\n\n\xa0\n\n1:17.3\n2.8\n\n\n\n\xa0\n\n9-9\n\xa0\n40.5\n510(-8)\n\n\n\xa0\n\n\n\n\n\xa0\n\nオンワードリーベ\n\xa0\n\n2012/05/24\n門別\n晴\n11\nスクリーンヒーロー賞\n\n\n\xa0\n\n\n12\n5\n6\n87.9\n11\n12\n\n桜井拓章\n\n56\nダ1700\n良\n\n\n\n\xa0\n\n1:56.1\n6.2\n\n\n\n\xa0\n\n1-1-8-12\n\xa0\n45.2\n518(+12)\n\n\n\xa0\n\n\n\n\n\xa0\n\nパパワパパラッチ\n\xa0\n\n2012/05/09\n門別\n晴\n9\n鈴蘭特別\n\n\n\xa0\n\n\n12\n7\n10\n28.1\n8\n11\n\n山口竜一\n\n56\nダ1200\n良\n\n\n\n\xa0\n\n1:18.0\n4.0\n\n\n\n\xa0\n\n4-5\n\xa0\n41.6\n506(-8)\n\n\n\xa0\n\n\n\n\n\xa0\n\nオンワードシュネル\n\xa0\n\n2012/04/25\n門別\n曇\n9\n八重桜特別\n\n\n\xa0\n\n\n9\n8\n10\n7.5\n5\n9\n\n桑村真明\n\n56\nダ1200\n稍\n\n\n\n\xa0\n\n1:17.2\n3.1\n\n\n\n\xa0\n\n7-8\n\xa0\n40.2\n514(+16)\n\n\n\xa0\n\n\n\n\n\xa0\n\nクラジェントリラブ\n\xa0\n\n2011/02/05\n2京都3\n曇\n7\n4歳以上500万下\n\n\n\n16\n2\n4\n468.9\n16\n12\n\n川島信二\n\n57\nダ1200\n良\n\n\n**\n\n\n1:14.3\n2.2\n\n\n**\n\n\n6-6\n35.0-37.1\n38.7\n498(-2)\n\n\n\n\n\n\n\xa0\n\nナムラカイシュウ\n\xa0\n\n2011/01/10\n1中山4\n晴\n8\n4歳以上500万下\n\n\n\n16\n5\n10\n79.7\n10\n10\n\n田中博康\n\n57\nダ1200\n良\n\n\n**\n\n\n1:13.4\n2.1\n\n\n**\n\n\n5-5\n33.4-37.9\n39.2\n500(+2)\n\n\n\n\n\n\n\xa0\n\nベストバウト\n\xa0\n\n2010/11/20\n3福島9\n晴\n6\n3歳以上500万下\n\n\n\n16\n3\n6\n51.6\n11\n9\n\n大野拓弥\n\n57\nダ1150\n良\n\n\n**\n\n\n1:09.6\n1.2\n\n\n**\n\n\n8-6\n31.4-37.0\n37.6\n498(+4)\n\n\n\n\n\n\n\xa0\n\nエイシンフルハート\n\xa0\n\n2010/11/06\n3福島5\n曇\n3\n3歳以上500万下\n\n\n\n12\n1\n1\n16.8\n5\n4\n\n大野拓弥\n\n57\nダ1000\n稍\n\n\n**\n\n\n1:00.5\n1.2\n\n\n**\n\n\n9-7\n34.6-36.1\n36.6\n494(-4)\n\n\n\n\n\n\n\xa0\n\nスピーディセイコー\n110.0\n\n2010/10/10\n4東京2\n曇\n7\n3歳以上500万下\n\n\n\n16\n2\n3\n81.2\n9\n12\n\n田中博康\n\n57\nダ1600\n重\n\n\n**\n\n\n1:39.3\n3.0\n\n\n**\n\n\n2-2\n35.2-37.9\n39.3\n498(-12)\n\n\n\n\n\n\n\xa0\n\nシルクパルサー\n\xa0\n\n2010/09/11\n2札幌1\n曇\n12\n手稲山特別(500万下)\n\n\n\n14\n1\n1\n21.8\n8\n11\n\n吉田隼人\n\n57\n芝1500\n良\n\n\n**\n\n\n1:31.0\n1.1\n\n\n**\n\n\n2-2-2\n29.6-35.8\n36.7\n510(0)\n\n\n\n\n\n\n\xa0\n\nアイアムマリリン\n\xa0\n\n2010/08/14\n1札幌1\n晴\n12\n3歳以上500万下\n\n\n\n16\n3\n5\n13.1\n6\n11\n\n大野拓弥\n\n57\n芝1200\n良\n\n\n**\n\n\n1:10.4\n1.1\n\n\n**\n\n\n10-9\n33.5-35.8\n36.1\n510(0)\n\n\n\n\n\n\n\n\nリキサンシンオー\n\xa0\n\n2010/08/01\n2函館6\n曇\n12\n3歳以上500万下\n\n\n\n15\n3\n5\n24.6\n10\n5\n\n大野拓弥\n\n57\n芝1200\n良\n\n\n**\n\n\n1:11.6\n0.3\n\n\n**\n\n\n3-3\n35.0-36.3\n36.3\n510(+2)\n\n\n\n\n\n\n\xa0\n\nピエナブラヴ\n74.0\n\n2010/07/17\n2新潟1\n晴\n9\n閃光特別(500万下)\n\n\n\n18\n2\n3\n23.2\n9\n12\n\n柴田善臣\n\n57\n芝1000\n良\n\n\n**\n\n\n0:55.5\n0.8\n\n\n**\n\n\n12\n32.0-33.2\n33.0\n508(+10)\n\n\n\n\n\n\n\xa0\n\nマヤノロシュニ\n\xa0\n\n2010/01/09\n1中山2\n晴\n12\n4歳以上500万下\n\n\n\n16\n7\n13\n37.8\n11\n8\n\n吉田隼人\n\n56\n芝1600\n良\n\n\n**\n\n\n1:35.0\n0.3\n\n\n**\n\n\n2-2-2\n34.6-36.4\n36.6\n498(-4)\n\n\n\n\n\n\n\xa0\n\nミサトバレー\n\xa0\n\n2009/11/18\n門別\n晴\n6\nえりも悲恋沼特別\n\n\n\xa0\n\n\n12\n7\n9\n5.6\n2\n1\n\n小国博行\n\n56\nダ1200\n不\n\n\n\n\xa0\n\n1:12.8\n-0.7\n\n\n\n\xa0\n\n1-1\n\xa0\n37.4\n502(0)\n\n\n\xa0\n\n\n\n\n\xa0\n\n(アメージングユー)\n25.0\n\n2009/10/28\n門別\n晴\n8\nJA共済3QC\n\n\n\xa0\n\n\n14\n5\n7\n2.4\n1\n4\n\n小国博行\n\n56\nダ1200\n稍\n\n\n\n\xa0\n\n1:15.8\n0.9\n\n\n\n\xa0\n\n4-4\n\xa0\n40.1\n502(-6)\n\n\n\xa0\n\n\n\n\n\xa0\n\nテツコジーン\n2.5\n\n2009/10/07\n門別\n晴\n6\nD1\u3000ー1組\n\n\n\xa0\n\n\n9\n5\n5\n1.6\n1\n1\n\n小国博行\n\n56\nダ1200\n稍\n\n\n\n\xa0\n\n1:15.9\n-0.5\n\n\n\n\xa0\n\n1-1\n\xa0\n38.8\n508(+22)\n\n\n\xa0\n\n\n\n\n\xa0\n\n(ロードオブペガサス)\n15.0\n\n2009/07/04\n2福島5\n曇\n7\n3歳未勝利\n\n\n\n15\n8\n14\n6.0\n3\n14\n\n吉田隼人\n\n56\nダ1700\n不\n\n\n**\n\n\n1:50.0\n4.6\n\n\n**\n\n\n6-6-10-13\n29.4-38.3\n41.7\n486(0)\n\n\n\n\n\n\n\xa0\n\nサイモントルナーレ\n\xa0\n\n2009/05/31\n3東京4\n曇\n4\n3歳未勝利\n\n\n\n18\n7\n14\n9.6\n6\n9\n\n田中博康\n\n56\n芝1400\n稍\n\n\n**\n\n\n1:24.3\n0.8\n\n\n**\n\n\n1-1\n36.0-35.2\n36.0\n486(0)\n\n\n\n\n\n\n\xa0\n\nアイティムサシ\n\xa0\n\n2009/03/14\n2中山5\n小雨\n5\n3歳未勝利\n\n\n\n15\n8\n15\n\xa0\n\xa0\n取\n\n津村明秀\n\n56\n芝1600\n重\n\n\n**\n\n\n\xa0\n\xa0\n\n\n**\n\n\n\xa0\n37.1-36.8\n\xa0\n計不\n\n\n\n\n\n\n\xa0\n\nコスモハート\n\xa0\n\n2008/11/29\n5東京7\n晴\n5\n2歳新馬\n\n\n\n10\n1\n1\n10.6\n4\n2\n\n田中博康\n\n54\n芝1400\n良\n\n\n**\n\n\n1:23.9\n0.1\n\n\n**\n\n\n1-1\n36.2-35.1\n35.2\n486(0)\n\n\n\n\n\n\n\xa0\n\nショウナンアルディ\n280.0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nビービーボルト関連ニュース\n\n\n\nnetkeibaニュース\n\n\nタレコミニュース\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nビービーボルト関連コラム\n\n\n\nnetkeibaコラム\n\n\nタレコミコラム\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n人気順\n\n\nコメント数\n\n\nレーティング\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n利用者数1700万人突破！No.1競馬サイト\n\n\n\n\nカテゴリ\n\n\n\nニュース\n\n\nレース\n\n\nウマい馬券\n\n\nコラム\n\n\nnetkeibaTV\n\n\n地方競馬\n\n\nデータベース\n\n\n俺プロ\n\n\n\n\n一口馬主\n\n\nPOG\n\n\n競馬広場\n\n\nまとめ\n\n\n競馬新聞\n\n\nお気に入り馬\n\n\nアカウント\n\n\n\n\n\nヘルプ＆ガイド\n\n\n\nお知らせ\n\n\nプレミアムサービスのご案内\n\n\nよくある質問・お問い合わせ\n\n\nのめり込む不安のある方へ\n\n\n\n\n\nnetkeibaについて\n\n\n\n採用情報\n\n\n広告掲載について\n\n\n利用規約\n\n\nプライバシーポリシー\n\n\n投稿ガイドライン\n\n\n特定商取引法に基づく表記\n\n\nライセンス\n\n\n運営会社\n\n\n\n\n\nスマホでnetkeiba\n\n\n\n\nアプリでサクサクnetkeiba\n\n\n\n\n\n\n\n\n\n\nみんなで一緒に競馬を楽しもう!\n\n\n\nnetkeibaをおすすめする\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nURLリンクをコピーしました\n\n\n\n\nnetkeiba公式SNS!\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nnetkeiba 公式競馬ゲーム\n\n\n\nみんなの愛馬とバトル！ うまいるスタジアム\n\n\n\nnetkeiba 姉妹サイト\n\n\n\n競輪総合メディア netkeirin(ネットケイリン)\n\n\n\n\n\n関連メディア\n\n\n\n徹底取材！野球情報は 週刊ベースボールONLINE\n\n\nゴルフレッスン情報サイト ワッグルオンライン\n\n\n小林カツ代直伝！ KATSUYOレシピ\n\n\n\n\n\nソフトウェア・プロダクト\n\n\n\nもっともセキュアな店舗売上向上アプリ SMART会員証\n\n\nスマホサイト制作ASP Let'sケータイ！\n\n\nサイト運営を劇的に効率化するCMS WEB SPIRAL\n\n\n\n\n\n\n© NET DREAMERS, Co., Ltd. All Rights Reserved.\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [46]:
tgtfilelist = glob.glob("../data/html/horse/*")

In [52]:
tgtfilelist = glob.glob("../data/html/ped/*")

In [47]:
len(tgtfilelist)

78335

In [50]:
from tqdm.notebook import tqdm

In [53]:
for file in tqdm(tgtfilelist):
    try:
        with open(file,"r",encoding="shift-jis") as f:
            txt = f.read()

        with  open(file,"w",encoding="utf-8") as f:
            f.write(txt)
    except Exception as e:
        pass

  0%|          | 0/78335 [00:00<?, ?it/s]

In [ ]:
from tqdm.notebook import tqdm
import pandas as pd
import glob